### ISSUE TITLE
Donation slider logic seems off - in this scenario, bottom two sliders should equal the same amount as only the top slider is being adjusted, but values move out of sync over time.

### ISSUE THREAD

**Issue by 03gibbss** [SmartCasual/jingle-jam#100]
https://imgur.com/a/iAnkXI1

**Comment by elliotcm** [comment]
I've not yet been satisfied with the code behind those sliders, but since the entire frontend is being replaced this falls under "won't fix" until that happens, since the code powering the sliders will be replaced along with it.
