### ISSUE TITLE
Donation sliders - see gif - this doesn't feel intuitive to me, I'm trying to set slidesr to 0 for the charities I don't want to donate to, but when I move another slider to 0 it brings it back up to offset the change in amount (gif demonstrates it better than my description)

### ISSUE THREAD

**Issue by 03gibbss** [SmartCasual/jingle-jam#101]
https://imgur.com/a/VxZb42U

Not sure on how best to fit this, if slider is at 0 then automatically lock slider? That also feels a bit unintuitive. To be honest I think having a button to lock the slider feels a bit weird anyway, but I'm not sure removing it would make it any more logical...

**Comment by elliotcm** [comment]
See https://github.com/SmartCasual/jingle-jam/issues/100
