### ISSUE TITLE
None of the donator / user pages work: https://jingle-jam-staging.herokuapp.com/en/donators/11

### ISSUE THREAD

**Issue by 03gibbss** [SmartCasual/jingle-jam#107]

**Comment by elliotcm** [comment]
Looks like this feature was never finished beyond what was needed to log in and out.  Do we have a record somewhere of what we wanted to show here?

**Comment by elliotcm** [comment]
We're going to temporarily remove the link to the donator's profile (see https://github.com/SmartCasual/jingle-jam/issues/129), and @03gibbss is going to fill out this issue with detail for what we'd like these pages to do.

**Comment by elliotcm** [comment]
This is now done as part of the account rework, though we could still do with having a more traditional profile edit (name etc).
