### ISSUE TITLE
Unable to delete bundle defintions

### ISSUE THREAD

**Issue by 03gibbss** [SmartCasual/jingle-jam#108]

**Comment by elliotcm** [comment]
You can, but the system won't allow you to delete bundle definitions if there's assigned key bundles associated with it, i.e. if it's in use.

The site should do a better job of handling that / indicating it, though.

**Comment by elliotcm** [comment]
This is being dealt with by being able to put definitions back into draft, and giving @03gibbss access to reset the staging database.
