### ISSUE TITLE
Seeing as the site creates you an account when you donate, it would be nice if it gave you the option to properly create an account with a proper username + password etc

### ISSUE THREAD

**Issue by 03gibbss** [SmartCasual/jingle-jam#111]
I imagine the journey for most people coming to the site will be:

- Visit the site directly from the twitch stream
- Go directly to make a donation
- Make payment (account gets automatically created for them)
- They are redirected to their game keys page
- If they log out or lose their unique url, they have no way to log back into the account (unless they are emailed login details / their unique url? - stripe doesn't seem to do anything with the email currently)

What would be nice is if when they go to make a donation is that they're prompted to make an account, or login with twitch, or something, with some text that says 'create an account / link to your twitch account to easily access your game keys' or something to that effect. (Of course we can still allow users to donate without an account).

Currently, every donation is from 'anonymous' too, so this would let them add a name, although we should probably have a name box for guests anyway.

(User pages don't seem to be working currently so maybe some of this sort of functionality already exists but I can't see it: https://jingle-jam-staging.herokuapp.com/en/donators/7)

**Comment by elliotcm** [comment]
I think this was probably related to the partially completed profile functionality.

Previously we were taking the email address from the Stripe payment and using that (which did result in an email to the donator with their magic URL) but we decided not to:
https://discord.com/channels/823548211397787718/823548211397787721/876823374507147294

Perhaps we can put that back.

We should also as you say add the ability for the donator to give their name and email address if they want when making a donation, that would be a quick change.
