### ISSUE TITLE
Localised storefronts

### ISSUE THREAD

**Issue by elliotcm** [SmartCasual/jingle-jam#14]
Localisation slows development down considerably but it's one of those things where once it's in, it's not so bad to maintain.

If we're doing it we should commit to doing it from day one of proper development, as it's always more effort to go back in after.

**Comment by GooBall** [comment]
@elliotcm Happy to pick this up 👍🏼

**Comment by GooBall** [comment]
@elliotcm I'd say I'm mostly done. I have a few questions though:

1) How do you want to distinguish access to different locals (url param/url path/something else)?
2) Do you care about any of the admin pages/login?
3) Do you have a preference on local file structure?

My recommendation would be:
1) url path "jinglejam.co.uk/fr/donate" for example. This can then be redirect to via UI, browser setting detection, or geo location. 
2) Only user facing things need translations for now.
3) Have a singe file per language (until/if it gets too large - we will have a better picture once the UI is being worked on properly).

What are your thoughts?

**Comment by elliotcm** [comment]
@GooBall I agree on points 2 and 3, and probably point 1 also.  @03gibbss do you have a preference on point 1 here?

**Comment by 03gibbss** [comment]
Sounds good to me

**Comment by GooBall** [comment]
Perfect 👌🏼  I'll finish up with the branch and you can have a look over it
