### ISSUE TITLE
Login via token is not working

### ISSUE THREAD

**Issue by 03gibbss** [SmartCasual/jingle-jam#176]
- http://jingle-jam-staging.herokuapp.com/account/request-- login-email
- enter email address
- open "log in via token" link in new window
- click login with token button
- Could not authenticate you from Token because "Invalid credentials".

**Comment by elliotcm** [comment]
Note to self:
This should use `token_with_email_address`, update the tests to ensure this URL is being used.
https://github.com/SmartCasual/jingle-jam/blob/main/app/mailers/notifications_mailer.rb#L38
