### ISSUE TITLE
Strict access controls for admins and donators

### ISSUE THREAD

**Issue by elliotcm** [SmartCasual/jingle-jam#38]
Add permission levels, control access to e.g. game keys, donator info.  Ensure access is checked for donators viewing their own keys.

Suggested admin permission levels:
- Support; can view donation, bundle, and donator info
- Data Entry; can view and edit games, bundle definitions etc, but not game keys
- Game Keys; can view and edit game keys
- Admin; has permissions of Support and Data Entry, plus can create/modify admin accounts for Support or Data Entry
- Full access; can do/see everything, including creating all non-full-access accounts (which should be very limited and probably added by hand)

**Comment by 03gibbss** [comment]
@elliotcm The suggested admin permissions look good to me - can't think of anything missing, and the way it's split makes sense. Let's proceed with that unless anyone else has any issue with this.
